commandsDir: '{{CWD}}/commands'
token: 'a token'
plugins:
  './commander.js':
    _dependencies:
      - 'hapi-slack-command'
  'hapi-method-loader':
    _enabled: false
  'hapi-route-loader':
    _enabled: false
  'hapi-slack-command':
    token: 'a token'
    _dependencies:
      - 'hapi-logr'
  'hapi-logr':
    reporters:
      flat:
        reporter: 'logr-flat'
        options:
