plugins:
  'hapi-method-loader':
    _enabled: false
  'hapi-route-loader':
    _enabled: false
  'hapi-slack-command':
    token: '{{getEnv("TOKEN")}}'
    commandDir: '{{CWD}}/commands'
    callbackDir: '{{CWD}}/callbacks'
    _dependencies:
      - 'hapi-logr'
